# Generated by Django 4.1.7 on 2023-03-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.CharField(default=1, max_length=64, verbose_name='邮件'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='qq',
            field=models.CharField(default=1, max_length=64, verbose_name='QQ'),
            preserve_default=False,
        ),
    ]
