# Generated by Django 4.1.7 on 2023-03-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_admin1'),
        ('app01', '0010_admin_email_admin_qq'),
    ]

    operations = [
    ]
